[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf

build_type = debug
monitor_speed = 115200
board_upload.flash_size = 2MB

upload_protocol = esptool

; Upload prin ESP-Prog 2 / JTAG, fără port COM
;upload_protocol = custom

;upload_command = C:/Espressif/tools/openocd-esp32/v0.12.0-esp32-20260424/openocd-esp32/bin/openocd.exe -s C:/Espressif/tools/openocd-esp32/v0.12.0-esp32-20260424/openocd-esp32/share/openocd/scripts -f board/esp32c3-bridge.cfg -c "program_esp .pio/build/esp32-c3-devkitm-1/firmware.bin 0x10000 verify reset exit"
