[platformio]
default_envs = esp32-c3-devkitm-1

[openocd]
executable = C:/Espressif/tools/openocd-esp32/v0.12.0-esp32-20260424/openocd-esp32/bin/openocd.exe
scripts = C:/Espressif/tools/openocd-esp32/v0.12.0-esp32-20260424/openocd-esp32/share/openocd/scripts

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
build_type = debug
monitor_speed = 115200

board_build.flash_size = 2MB
board_upload.flash_size = 2MB
board_build.esp-idf.sdkconfig_path = sdkconfig.esp32-c3-devkitm-1

; Debug prin ESP-PROG 2 / JTAG.
; Pornirea depanarii nu declanseaza automat un upload.
debug_load_mode = manual
debug_tool = custom
debug_port = :3333
debug_init_break = thbreak app_main

debug_server =
    ${openocd.executable}
    -s
    ${openocd.scripts}
    -f
    board/esp32c3-bridge.cfg

debug_server_ready_pattern = Listening on port 3333 for gdb connections

debug_init_cmds =
    define pio_reset_halt_target
        monitor reset halt
    end
    define pio_reset_run_target
        monitor reset
    end
    target extended-remote $DEBUG_PORT
    monitor reset halt
    $INIT_BREAK
    continue

; Upload prin portul USB nativ al placii.
upload_protocol = esptool
upload_port = COM11

[env:esp32-c3-devkitm-1-full]
extends = env:esp32-c3-devkitm-1

; Mediul complet foloseste acelasi upload USB prin esptool.
